### ISSUE TITLE
Deformazione del logo

### ISSUE THREAD

**Issue by acaland** [acaland/SmartMe#1]
Ho notato una piccola deformazione del logo quando  l’applicazione viene aperta.

![image](https://user-images.githubusercontent.com/3988594/162413058-574b65e3-a0c2-4925-a526-fe1dc7ec3d0c.png)

**Comment by Astrovic** [comment]
Bisognerebbe creare tutti gli assets in modalità landscape, attualmente sono presenti solo quelli in portrait.
Ancora meglio sarebbe utilizzare semplicemente l'app icon, ed impostare il colore di sfondo, come tra l'altro è previsto dalle nuove linee guida Android per gli splash screen https://developer.android.com/guide/topics/ui/splash-screen

**Comment by Astrovic** [comment]
Ho aggiornato gli asset grafici usando le nuove linee guida.
Inoltre adesso l'app è compatibile anche con Android 12.
Le modifiche sono state apportate [nel commit](https://bitbucket.org/Astrovic/smartme-test/commits/ee5e7559f04f7f86a993eab3f865e8c025db4589).

Questa è la release dell'app con le ultime modifiche: https://github.com/acaland/SmartMe/releases/download/android-1.0.2/SmartMe.You.apk
