### ISSUE TITLE
task troppo piccoli

### ISSUE THREAD

**Issue by andreeammusat** [acaland/SmartMe#10]
difficoltà a selezionare i task, poiché la colonna è troppo stretta. vanno aumentati anche i caratteri di scrittura. in modo che una persona anziana le riesca a vedere bene!
![Screenshot_2022-05-06-12-23-47](https://user-images.githubusercontent.com/103252970/167114812-a0e6f3d8-4bf8-4e2a-9ef1-22b069cb6135.png)

**Comment by Astrovic** [comment]
Chiudo perché duplicato della https://github.com/acaland/SmartMe/issues/9
