### ISSUE TITLE
Pulsanti ISTRUZIONI e AVVIA che precedono l'avvio di un compito

### ISSUE THREAD

**Issue by Astrovic** [acaland/SmartMe#11]
All'avvio di ogni compito l'app mostra questo popup per accedere alle istruzioni o avviare il compito.

![istruzioni e avvio](https://user-images.githubusercontent.com/2573811/177121313-067620cb-ac17-4337-932c-9f600bd31fef.jpg)

Per facilitare la selezione delle due opzioni, potremmo utilizzare un pulsante blu per l'opzione **Istruzioni** e verde per **Avvia**, come questi utilizzati nella Home

![pulsanti home](https://user-images.githubusercontent.com/2573811/177123331-9b7a132e-ca59-4b04-802e-700eb67a2d7d.jpg)

**Comment by Astrovic** [comment]
Questo è il popup coi nuovi pulsanti che precede l'esecuzione del Compito 1. Se va bene procedo ad implementarlo in tutti i compiti.

![pulsanti nuovi](https://user-images.githubusercontent.com/2573811/177261794-67afffa7-8c99-4444-8670-f11bb3198724.jpg)

**Comment by Astrovic** [comment]
Sulla base di quanto discusso stamattina, ho implementato un altro prototipo che include istruzioni con immagini. 

![istruzioni visive](https://user-images.githubusercontent.com/2573811/177302568-420b684b-a59d-43bc-9467-53f52d960d15.jpg)

![istruzioni visive portrait](https://user-images.githubusercontent.com/2573811/177303911-4c3d92fb-3c2a-4179-a50e-14a0197057dd.jpg)

**Comment by Astrovic** [comment]
Questo è il popup con la versione illustrata delle istruzioni del compito 1.
Il popup è a scorrimento verticale, in modo da consentire l'intera visualizzazione dell'immagine, mentre i pulsanti **Istruzioni** e **Avvia** rimangono fissi nella parte bassa del popup.

![istruzioni-immagine](https://user-images.githubusercontent.com/2573811/177524718-95e1eb38-1648-4f61-bc24-b8eab8d5d021.jpg)

**Comment by Astrovic** [comment]
Nella release 1.0.3 https://github.com/acaland/SmartMe/releases/tag/android-1.0.3 sono state implementate le 7 vignette (ancora in fase di approvazione) realizzate da @andreeammusat

Questo è il link diretto per il download dell'app: https://github.com/acaland/SmartMe/releases/download/android-1.0.3/SmartMe.You.apk

--
_Modifiche: [commit](https://bitbucket.org/Astrovic/smartme-test/commits/afc878cc7bf5afae86b7e60c2924fc2cb76409a4)_

**Comment by andreeammusat** [comment]
> Questo è il popup con la versione illustrata delle istruzioni del compito 1. Il popup è a scorrimento verticale, in modo da consentire l'intera visualizzazione dell'immagine, mentre i pulsanti **Istruzioni** e **Avvia** rimangono fissi nella parte bassa del popup.
> 
> ![istruzioni-immagine](https://user-images.githubusercontent.com/2573811/177524718-95e1eb38-1648-4f61-bc24-b8eab8d5d021.jpg)

cortesemente potresti, diminuire le dimensioni del tasto "istruzioni "

**Comment by Astrovic** [comment]
Ho diminuito le dimensioni del pulsante **ISTRUZIONI** e l'ho spostato a sinistra. Il pulsante **AVVIA** l'ho posizionato centralmente. Se va bene, procedo con una nuova release.

![istruzioni-avvia](https://user-images.githubusercontent.com/2573811/178003834-54ef0b64-53d3-45db-a043-be549b9a6548.jpg)

**Comment by Astrovic** [comment]
Nella release 1.0.4 https://github.com/acaland/SmartMe/releases/tag/android-1.0.4 sono state aggiornate le istruzioni grafiche realizzate da @andreeammusat utilizzando l'ultima versione approvata. Inoltre sono stati modificati i pulsanti **ISTRUZIONI** e **AVVIA** come da immagine precedente.

Questo è il link diretto per il download dell'app: https://github.com/acaland/SmartMe/releases/download/android-1.0.4/SmartMe.You.apk

--
_Modifiche: [commit](https://bitbucket.org/Astrovic/smartme-test/commits/3ecd1750f2412f49ca2b303058d8d3dbcc939317)_
