### ISSUE TITLE
dicitura al termine del task

### ISSUE THREAD

**Issue by andreeammusat** [acaland/SmartMe#15]
otresti cortesemente modificare le scritte che compaiono al termine dei Compiti?
Adesso c’è scritto “Fine compito1”, invece potresti scrivere  “fine Prova” senza indicare il numero della prova che si è svolta?
ecco come è adesso 
![Screenshot_20220705-142448](https://user-images.githubusercontent.com/103252970/177784911-01b5b986-89a4-4034-80d9-9879f6092618.jpg)

cosi dovrebbe comparire
![Screenshot_20220706-123016](https://user-images.githubusercontent.com/103252970/177785152-93811ccd-a1d1-4266-960d-bb426e9929d2.jpg)

**Comment by Astrovic** [comment]
Va bene, adesso comparirà **FINE PROVA** al posto di **FINE COMPITO N**, come richiesto.

Faccio presente che nella versione attuale la dicitura **FINE PROVA** compare più volte all'interno di un compito, in quanto un compito può avere N prove. Di conseguenza **FINE COMPITO** indicava che non ci fossero ulteriori prove.
In ogni caso, a fine compito adesso compare il popup coi pulsanti **SUCCESSIVO** e **CHIUDI**, che riporta anche la descrizione **FINE COMPITO** (https://github.com/acaland/SmartMe/issues/12#issuecomment-1175999692)

**Comment by Astrovic** [comment]
Modifica apportata nella release 1.0.4 https://github.com/acaland/SmartMe/releases/tag/android-1.0.4.

Questo è il link diretto per il download dell'app: https://github.com/acaland/SmartMe/releases/download/android-1.0.4/SmartMe.You.apk

--
_Modifiche: [commit](https://bitbucket.org/Astrovic/smartme-test/commits/3ecd1750f2412f49ca2b303058d8d3dbcc939317)_
