### ISSUE TITLE
tasti molto più grandi  tipo: BRONDI

### ISSUE THREAD

**Issue by andreeammusat** [acaland/SmartMe#18]
cortesemente, aumentare le minestrone dei tasti, senza stravolgere la grafica, ciò significa che :
![Screenshot_20220728-143244](https://user-images.githubusercontent.com/103252970/181507640-92fb68a8-2ab7-4878-a3f3-f3b70cbbd57d.jpg)
tasto "chiudi" deve ricoprire tutto lo spazio , in altezza , della linea blu 
![Screenshot_20220728-143227](https://user-images.githubusercontent.com/103252970/181507854-d7e908e3-40a5-4e67-83ce-1d0a9ad82203.jpg)
stessa cosa, con il tasto avvia, che deve rientrare in tutto lo spazio disponibile per il bottone , le istruzioni le dobbiamo ingrandire , magari possiamo ingrandire sia il tasto "avvia" sia il tasto "istruzioni" , affinché le proporzioni rimangano uguali 
![Screenshot_20220728-143249](https://user-images.githubusercontent.com/103252970/181508187-988d55f9-4a97-430e-bb2f-87827531473a.jpg)
L'elenco dei compiti deve essere piu grande, il prof. propone di utilizzare tutto lo spazio disponibile, affinché non ci siano spazzi vuoti, magari possiamo aumentare la larghezza della colonna che elenca i compiti.
![Screenshot_20220728-143234](https://user-images.githubusercontent.com/103252970/181510572-c43045bc-d165-4592-9d06-0f1b572798b3.jpg)
 ti chiedo di aumentare la scritta "chiudi" in modo da ricoprire tutto lo spazio in altezza, della striscia blu 

Scusami tanto.
Andreea

**Comment by Astrovic** [comment]
Ho ingrandito le dimensioni del testo e del pulsante **CHIUDI** sulla actionbar in alto a destra, per interrompere l'esecuzione del compito.
![esecuzione compito](https://user-images.githubusercontent.com/2573811/189380886-890dbd21-7236-46be-b911-2cf8d973276d.jpg)

Ho ingrandito il testo del pulsante **AVVIA** e le dimensioni del pulsante **ISTRUZIONI** (mantenendolo comunque più piccolo rispetto al pulsante **AVVIA**) e utilizzando anche il testo maiuscolo per renderli più evidenti.
Ho anche aggiunto il pulsante **CHIUDI** in rosso in alto a destra nella actionbar.
![IMAGE 2022-09-09 17:15:15](https://user-images.githubusercontent.com/2573811/189384120-e769720c-0706-4740-b01e-3a0d30ddfcf8.jpg)

Ho aggiunto il pulsante **INIZIO PROVA**  come richiesto anche nella issue https://github.com/acaland/SmartMe/issues/19, ingrandendo il pulsante in alto destra nella ationbar
![Istruzioni compito](https://user-images.githubusercontent.com/2573811/189379504-03162ae7-6f20-44a9-8694-026ee1526da4.jpg)

Le dimensioni dei testi dipendono dalla risoluzione del device. Ad esempio nello screenshot seguente, fatto su un tablet 10", gli spazi vuoti sono di meno. Poi c'è anche l'elenco dei compiti eseguiti, che si aggiorna man mano che si completano i compiti, riempendo spazio. C'era anche un bug nella versione 1.6.0, come riportato nella issue https://github.com/acaland/SmartMe/issues/20#issuecomment-1242078110 che non faceva visualizzare i dati dell'operatore e del paziente, dunque altro spazio che si riempie.
In genere è buona norma utilizzare dimensioni dei testi differenti a seconda che si tratti di titoli, sottotitoli, paragrafi, pulsanti, elenchi ecc... e mantenerle inalterate in tutte le pagine, così che l'utente a colpo d'occhio capisca qual è la gerarchia dei testi e riconosca facilmente gli elementi grafici. Dunque graficamente sarebbe davvero brutto aumentare la larghezza della colonna con l'elenco dei compiti o la loro dimensione solo per "riempire il vuoto".
![Home compiti 16:52:15](https://user-images.githubusercontent.com/2573811/189379086-58361174-2496-4b53-b8f0-8a715fb6cd27.jpg)

**Comment by Astrovic** [comment]
Modifiche implementate nella release 1.0.7 https://github.com/acaland/SmartMe/releases/tag/android-1.0.7

Questo è il link diretto per il download della versione Android: https://github.com/acaland/SmartMe/releases/download/android-1.0.7/SmartMe.apk

Build iOS su TestFlight: https://testflight.apple.com/v1/app/1535177677?build=96649353

--
Modifiche: [commit](https://bitbucket.org/Astrovic/smartme-test/commits/b04b17f1430bd1d298dc2b6c53c89f38c2a52718)

**Comment by Astrovic** [comment]
Modifiche implementate nella release 1.0.7 https://github.com/acaland/SmartMe/releases/tag/android-1.0.7

Questo è il link diretto per il download della versione Android: https://github.com/acaland/SmartMe/releases/download/android-1.0.7/SmartMe.apk

Build iOS su TestFlight: https://testflight.apple.com/v1/app/1535177677?build=96649353

--
Modifiche: [commit](https://bitbucket.org/Astrovic/smartme-test/commits/b04b17f1430bd1d298dc2b6c53c89f38c2a52718)
