### ISSUE TITLE
tasto avvia compito

### ISSUE THREAD

**Issue by andreeammusat** [acaland/SmartMe#19]
![Screenshot_20220728-143234](https://user-images.githubusercontent.com/103252970/181511163-9f1179f5-c9e0-41c3-bb63-e94d1269d1ea.jpg)
il prof chiederebbe che : una volta che il paziente legge le istruzioni, ci dovrebbe essere, un pulsante che lo porti ad iniziare il task per cui legge le istruzioni, del tipo: "avvia compito" in verde, a caratteri molto grandi.

**Comment by Astrovic** [comment]
Va bene ho inserito il pulsante **INIZIO PROVA** in basso al centro, così come nella pagina con le istruzioni illustrate.
Inoltre ho anche ingrandito il pulsante **INIZIO PROVA** sull'actionbar in alto a destra per renderlo più visibile e cliccabile con maggior facilità.

![Istruzioni compito](https://user-images.githubusercontent.com/2573811/189379504-03162ae7-6f20-44a9-8694-026ee1526da4.jpg)

**Comment by Astrovic** [comment]
Modifica implementata nella release 1.0.7 https://github.com/acaland/SmartMe/releases/tag/android-1.0.7

Questo è il link diretto per il download della versione Android: https://github.com/acaland/SmartMe/releases/download/android-1.0.7/SmartMe.apk

Build iOS su TestFlight: https://testflight.apple.com/v1/app/1535177677?build=96649353

--
Modifiche: [commit](https://bitbucket.org/Astrovic/smartme-test/commits/b04b17f1430bd1d298dc2b6c53c89f38c2a52718)

**Comment by Astrovic** [comment]
Modifica implementata nella release 1.0.7 https://github.com/acaland/SmartMe/releases/tag/android-1.0.7

Questo è il link diretto per il download della versione Android: https://github.com/acaland/SmartMe/releases/download/android-1.0.7/SmartMe.apk

Build iOS su TestFlight: https://testflight.apple.com/v1/app/1535177677?build=96649353

--
Modifiche: [commit](https://bitbucket.org/Astrovic/smartme-test/commits/b04b17f1430bd1d298dc2b6c53c89f38c2a52718)
