### ISSUE TITLE
export dati non riuscito 

### ISSUE THREAD

**Issue by andreeammusat** [acaland/SmartMe#2]
![image](https://user-images.githubusercontent.com/103252970/162414896-47d5471e-255c-44c0-aca9-d3ff810e6278.png)
ho provato ad inviare i risultati del test, dall’app alla mia mail, pero quello che ne risulta è una mail con solo nome e nessun file excel allegato.

**Comment by acaland** [comment]
farò delle verifiche e vi aggiorno

**Comment by Astrovic** [comment]
L'allegato del file HTML non è presente su un device specifico o nemmeno sugli altri device? 
Forse è stato negato il permesso alla richiesta di accesso all'archivio. Si può verificare dalle impostazioni del device dal menu Impostazioni > App > SmartMe&You > Autorizzazioni (il percorso del menu potrebbe essere diverso su alcuni device)

![Schermata 2022-05-18 alle 18 39 30](https://user-images.githubusercontent.com/2573811/169096281-61ec07bf-e8fb-4919-8b0f-a975841c82ba.png)

**Comment by andreeammusat** [comment]
BUONGIORNO, con la nuova versione funziona !
il file viene inviato come html che può essere aperto con excel 
grazie

**Comment by Astrovic** [comment]
Benissimo, grazie per il feedback. Chiudo la issue
