### ISSUE TITLE
Testo della giornata.

### ISSUE THREAD

**Issue by andreeammusat** [acaland/SmartMe#20]
![Screenshot_20220728-143249](https://user-images.githubusercontent.com/103252970/181511951-9f1babb6-b2ab-4130-8ed9-2c6c23bf09f8.jpg)
 queste informazioni vengono prese direttamente dal sistema? e vengono formattate secondo quanto riporta il Sistema Operativo?
ad esempio: Giovedì 28 Luglio 2022, giovedì scritto con la lettera maiuscola, viene ripreso da come è riportato dal sistema operativo?
se cosi non fosse è una sgrammaticatura, e lo dovremmo correggere.

**Comment by Astrovic** [comment]
Le informazioni relative alla data e l'ora sono prese dal device in uso, ma è possibile formattare l'intero testo in maiuscolo o minuscolo, direi di utilizzare il minuscolo dunque.
Inoltre nella versione attuale ([1.6.0](https://github.com/acaland/SmartMe/releases/tag/android-1.0.6)) c'è un bug che omette le informazioni relative all'operatore ed al paziente. Saranno ripristinate nella nuova release.
Di seguito un'anteprima

![Home compiti 16:52:15](https://user-images.githubusercontent.com/2573811/189379086-58361174-2496-4b53-b8f0-8a715fb6cd27.jpg)

**Comment by Astrovic** [comment]
Modifica implementata nella release 1.0.7 https://github.com/acaland/SmartMe/releases/tag/android-1.0.7

Questo è il link diretto per il download della versione Android: https://github.com/acaland/SmartMe/releases/download/android-1.0.7/SmartMe.apk

Build iOS su TestFlight: https://testflight.apple.com/v1/app/1535177677?build=96649353

--
Modifiche: [commit](https://bitbucket.org/Astrovic/smartme-test/commits/b04b17f1430bd1d298dc2b6c53c89f38c2a52718)

**Comment by Astrovic** [comment]
Modifica implementata nella release 1.0.7 https://github.com/acaland/SmartMe/releases/tag/android-1.0.7

Questo è il link diretto per il download della versione Android: https://github.com/acaland/SmartMe/releases/download/android-1.0.7/SmartMe.apk

Build iOS su TestFlight: https://testflight.apple.com/v1/app/1535177677?build=96649353

--
Modifiche: [commit](https://bitbucket.org/Astrovic/smartme-test/commits/b04b17f1430bd1d298dc2b6c53c89f38c2a52718)
