### ISSUE TITLE
invio sessioni

### ISSUE THREAD

**Issue by andreeammusat** [acaland/SmartMe#22]
non riesco piu ad inviare le sessioni che ho concluso. 
non è una questione di internet, perché ho potuto scaricare il nuovo aggiornamento, e ho navigato in internet.
questo problema persiste dal 4 luglio, ultimo invio delle sessioni concluse risale al 10 giugno!

**Comment by Astrovic** [comment]
Il problema era causato dall'interruzione del server del GARR. Il servizio è stato ripristinato, adesso dovrebbe essere possibile inviare le sessioni, comprese le vecchie non ancora inviate.
A partire dalla [release 1.8.0](https://github.com/acaland/SmartMe/releases/tag/android-1.0.8) sono inoltrati al server anche i dati del compito 8.
