### ISSUE TITLE
reset password 

### ISSUE THREAD

**Issue by andreeammusat** [acaland/SmartMe#3]
ho provato a fare il reset del pin per accedere al archivio, purtroppo non viene aggiornata, mi fa entrare sempre con quella di default: 1234

**Comment by acaland** [comment]
A quale PIN ti riferisci? Puoi mandarmi uno o più screenshot dell'operazione?

**Comment by andreeammusat** [comment]
![Screenshot1](https://user-images.githubusercontent.com/103252970/164466147-150d695e-85e6-4bb7-8408-765cbf3a07e6.png)
![Screenshot_2](https://user-images.githubusercontent.com/103252970/164466158-94a99a06-0eaf-436a-b770-0a44228c3746.png)

**Comment by Astrovic** [comment]
**1234** è il PIN di default. Dunque col pulsante **Reset PIN** verrà richiesto il login dell'utente, e successivamente sarà impostato il PIN di default **1234**.
Per modificare il PIN invece bisogna usare il pulsante **Modifica PIN**. Si aprirà una nuova finestra per confermare il PIN attuale ed il nuovo PIN.

**Comment by Astrovic** [comment]
Spero che sia stato chiarito il procedimento. In caso di dubbi è sempre possible commentare o riaprire questa stessa issue.

**Comment by andreeammusat** [comment]
si, è stato chiaro, però le modifiche apportate al pin, sul mio account, non vengono salvate su altri dispositivi. 
ad esempio quando cerco di inserire il pin su altri tablet, non mi consente di entrare con il pin modificato in precedenza ma con quello di default:1234

**Comment by Astrovic** [comment]
Questo PIN è associato al dispositivo, non all'account dell'operatore. Di conseguenza è memorizzato solo sul dispositivo in uso.
