### ISSUE TITLE
ordine casuale dei test eseguiti 

### ISSUE THREAD

**Issue by andreeammusat** [acaland/SmartMe#4]
![screeen](https://user-images.githubusercontent.com/103252970/165286197-145c4e92-7e7d-4371-a8ca-098b3e6de3ce.png)

i test sono eseguiti nell'ordine : 1, 2 , 3.. non vengono archiviati nello stesso modo ma in un modo casuale.

**Comment by Astrovic** [comment]
Bug risolto [nel commit](https://bitbucket.org/Astrovic/smartme-test/commits/b3b38fd294ee22f304cb93a4d7f2ec59bed6cfec).
Versione aggiornata: https://github.com/acaland/SmartMe/releases/download/android-1.0.0/SmartMe.You.apk
