### ISSUE TITLE
Sostituzione SmartMe con SmartMe&You

### ISSUE THREAD

**Issue by EtnaTraining** [acaland/SmartMe#5]
Rebranding dei testi, nome app, etc in SmartMe&You

**Comment by Astrovic** [comment]
L'utilizzo della **`&`** nel nome dell'app richiede una modifica alla configurazione della CLI per poter eseguire la build.

![smartme you-log](https://user-images.githubusercontent.com/2573811/166726492-3772c1b4-e90e-4354-9040-ea1a891b066d.png)

Come suggerito dal log, sarà necessario impostare `ti config android.allowAppNameAmpersands true`

Modifica apportata nel [commit](https://bitbucket.org/Astrovic/smartme-test/commits/af8e35aa2b2ca88d9a3ab17f76685b6c270dc9a7 )

**Comment by andreeammusat** [comment]
salve, non ho capito, potrebbe essere più chiaro? devo impostare qualcosa io sul tablet ?

**Comment by Astrovic** [comment]
No non serve nessuna modifica, sono solo istruzioni per il deployment dell'app
