### ISSUE TITLE
istruzioni in inglese 

### ISSUE THREAD

**Issue by andreeammusat** [acaland/SmartMe#6]
[tasks in English new!.docx](https://github.com/acaland/SmartMe/files/8638567/tasks.in.English.new.docx)

**Comment by EtnaTraining** [comment]
Mi ricordi dove vanno inserite queste istruzioni?

**Comment by andreeammusat** [comment]
prima di iniziare ogni task, appare una finestra con due pulsanti: istruzioni ed avvia .
se tu clicchi istruzioni dovrebbe comparire la descrizione in inglese. 
![Unknown](https://user-images.githubusercontent.com/103252970/167104259-272aac99-f136-4f70-8584-8ad47b4eacb8.png)

![Screenshot_2022-05-06-10-53-50](https://user-images.githubusercontent.com/103252970/167104387-09794c8d-0348-4e32-8d1a-7d128db1337a.png)

**Comment by EtnaTraining** [comment]
perfetto! Grazie mille. Puoi provare per piacere cosa succede al momento nella versione inglese?

**Comment by andreeammusat** [comment]
> perfetto! Grazie mille. Puoi provare per piacere cosa succede al momento nella versione inglese?

quello che ho provato è la versione in lingua inglese.

**Comment by EtnaTraining** [comment]
ok, quindi di fatto i test NON tradotti in inglese, appaiono in italiano. Grazie per il test. Ci aggiorniamo a breve

**Comment by Astrovic** [comment]
Confermo che nelle versioni precedenti erano utilizzate solo le istruzioni in italiano, non avendo la traduzione in inglese.
I testi forniti sono stati inseriti [nel commit](https://bitbucket.org/Astrovic/smartme-test/commits/b3b38fd294ee22f304cb93a4d7f2ec59bed6cfec).
Versione aggiornata: https://github.com/acaland/SmartMe/releases/download/android-1.0.0/SmartMe.You.apk
