### ISSUE TITLE
versione in lingua inglese 

### ISSUE THREAD

**Issue by andreeammusat** [acaland/SmartMe#7]
![Unknown](https://user-images.githubusercontent.com/103252970/167104496-279bd8a9-ba95-4a8d-b4d8-cf57374f1da4.png)
 dovrebbero essere tradotte anche opzioni "avvia" e "istruzioni " , che nella versione in lingua inglese rimangono in italiano

**Comment by Astrovic** [comment]
Testi tradotti [nel commit](https://bitbucket.org/Astrovic/smartme-test/commits/b3b38fd294ee22f304cb93a4d7f2ec59bed6cfec).
Versione aggiornata: https://github.com/acaland/SmartMe/releases/download/android-1.0.0/SmartMe.You.apk
