### ISSUE TITLE
traduzione in turco

### ISSUE THREAD

**Issue by acaland** [acaland/SmartMe#8]
Ecco il file che determina i testi di tutti gli elementi di interfaccia dell'app:

[https://github.com/acaland/SmartMe/blob/main/strings.xml](https://github.com/acaland/SmartMe/blob/main/strings.xml)

Dopo averlo scaricato, andrebbe modificato traducendo solo il testo **compreso** tra i tag. Ad esempio, per la riga:

```
<string name="compito_1">Compito 1</string>
```

dovrebbe diventare in Turco:

```
<string name="compito_1">Görev 1</string>
```
Se ho tradotto correttamente :-)

Al termine poi carica il nuovo file tradotto nella sezione <Code> cosi provvediamo ad aggiornare l'app.

**Comment by andreeammusat** [comment]
[Tasks Turco_EY.docx](https://github.com/acaland/SmartMe/files/8698753/Tasks.Turco_EY.docx)

buongiorno, ecco il file della descrizione dei task in turco

**Comment by andreeammusat** [comment]
mi potresti mandare le stringhe in inglese, se le abbiamo ?
grazie

**Comment by Astrovic** [comment]
I testi delle istruzioni in turco sono stati inseriti [nel commit](https://bitbucket.org/Astrovic/smartme-test/commits/b3b38fd294ee22f304cb93a4d7f2ec59bed6cfec).
Versione aggiornata: https://github.com/acaland/SmartMe/releases/download/android-1.0.0/SmartMe.You.apk

Queste sono le stringhe in lingua inglese: https://github.com/acaland/SmartMe/blob/main/strings-en.xml

**Comment by andreeammusat** [comment]
salve, 

mi sono state inviatel'altro giorno, le stringhe tradotte in inglese, da Antonio, ho provato a tradurre  in Turco, appena avrò la correzione della traduzione , le invierò il tutto. 

la ringrazio 
cordialmente 
Andreea

**Comment by Astrovic** [comment]
Benissimo, le ho aggiunte al progetto per averle sempre disponibili qualora servissero in futuro. Chiuderò questa issue appena saranno pronte quelle in turco.

**Comment by andreeammusat** [comment]
[xml version turco.docx](https://github.com/acaland/SmartMe/files/8737627/xml.version.turco.docx)

**Comment by Astrovic** [comment]
Benissimo, ho aggiunto le stringhe nel file: https://github.com/acaland/SmartMe/blob/main/strings-tr.xml

Manca però la traduzione delle due stringhe che nella vecchia versione erano tradotte solo in italiano:
`Avvia` https://github.com/acaland/SmartMe/blob/main/strings-tr.xml#L12
`Istruzioni` https://github.com/acaland/SmartMe/blob/main/strings-tr.xml#L13.

Usando Google Translate dovrebbero essere:
```xml
<string name="avvia">Başlangıç</string>
<string name="istruzioni">Talimatlar</string>
```

Attendo conferma o la traduzione corretta, anche qui nei commenti, così procedo ad aggiornare il file e pubblicare una nuova release dell'app.

**Comment by andreeammusat** [comment]
perfetto 
grazie mille

**Comment by Astrovic** [comment]
Attendo conferma sulla traduzione delle due stringhe: **`Avvia --> Başlangıç`** e **`Istruzioni --> Talimatlar`**
Se la traduzione va bene, creo una nuova release.

**Comment by andreeammusat** [comment]
Start: Başlama, başla
instructions: yönergeler, açıklamalar

**Comment by Astrovic** [comment]
Grazie, allora utilizzo

```xml
<string name="avvia">Başlama</string>
<string name="istruzioni">Yönergeler</string>
```

**Comment by Astrovic** [comment]
Aggiunta la traduzione in turco, [qui il commit](https://bitbucket.org/Astrovic/smartme-test/commits/94aa3acba3c3b26db95535398b925ac4d9987552)

Ho aggiornato le stringhe nel file: https://github.com/acaland/SmartMe/blob/main/strings-tr.xml

Questa è la release dell'app con le ultime modifiche: https://github.com/acaland/SmartMe/releases/download/android-1.0.1/SmartMe.You.apk
