### ISSUE TITLE
tasti troppo piccoli

### ISSUE THREAD

**Issue by andreeammusat** [acaland/SmartMe#9]
difficoltà a selezionare i task, poiché la colonna è troppo stretta. vanno aumentati anche i caratteri di scrittura. in modo che una persona anziana le riesca a vedere bene!
![Screenshot_2022-05-06-12-23-47](https://user-images.githubusercontent.com/103252970/167114812-a0e6f3d8-4bf8-4e2a-9ef1-22b069cb6135.png)

**Comment by Astrovic** [comment]
Le modifiche richieste sono state apportate [nel commit](https://bitbucket.org/Astrovic/smartme-test/commits/b3b38fd294ee22f304cb93a4d7f2ec59bed6cfec).
Versione aggiornata: https://github.com/acaland/SmartMe/releases/download/android-1.0.0/SmartMe.You.apk
